export {
  DEFAULT_DICE_APPEARANCE,
  DEFAULT_DICE_FACE_LABEL_MODE,
  DEFAULT_DICE_FONT_APPEARANCE,
  DEFAULT_ENGRAVING_DEPTH,
  MAX_DICE_FONT_SIZE,
  MAX_ENGRAVING_DEPTH,
  MIN_DICE_FONT_SIZE,
  MIN_ENGRAVING_DEPTH,
  hasDiceTextureSources,
  mergeDiceAppearances,
  resolveDiceAppearance,
  resolveDiceFaceLabelMode,
  resolveDiceFontAppearance,
  type DiceAppearance,
  type DiceFaceLabelMode,
  type DiceFontAppearance,
  type ResolvedDiceAppearance,
  type ResolvedDiceFontAppearance
} from "./appearance/index.js";
export {
  DiceRoller,
  D6_FACE_NORMALS,
  D6_FACE_VALUES,
  D6_OPPOSITE_FACE,
  D6_REFERENCE_EDGE_MM,
  SUPPORTED_DICE_SIDES,
  SeededRandomProvider,
  createSeededRandomProvider,
  getD6TopValue,
  getDiceFace,
  getDiceTopology,
  getDiceValueFromOrientation,
  type D6FaceNormal,
  type D6FaceValue,
  type DiceDefinition,
  type DiceResultDirection,
  type DiceRollerOptions,
  type DiceRollRequest,
  type DiceRollResult,
  type DiceSides,
  type DiceTopology,
  type DiceTopologyFace,
  type DiceVector3 as DiceTopologyVector3,
  type DieResult,
  type QuaternionLike,
  type RandomProvider,
  type RandomSeed,
  type RollIdProvider
} from "./core/index.js";
export {
  DICE_ROLL_EVENT_TYPE,
  DICE_ROLL_EVENT_VERSION,
  DICE_ROLL_REPLAY_VERSION,
  createDiceRollEvent,
  diceRollResultFromEvent,
  validateDiceRollEvent,
  type CreateDiceRollEventOptions,
  type DiceRollEvent,
  type DiceRollEventDie,
  type DiceRollReplayV1
} from "./events/index.js";
export {
  DiceOverlay,
  DiceOverlayError,
  type DiceOverlayErrorPhase,
  type DiceOverlayOptions,
  type DiceOverlayPlanner,
  type DiceOverlayPlayer,
  type DiceOverlayPlayerFactory,
  type DiceOverlayRenderer,
  type DiceOverlayRendererFactory,
  type DiceOverlayRollOptions,
  type DiceOverlayRoller
} from "./overlay/index.js";
export {
  BackgroundRollPlanner,
  DirectRollPlanner,
  DEFAULT_DICE_PHYSICS_CONFIG,
  DEFAULT_STABILITY_CONFIG,
  DEFAULT_THROW_FORCE,
  MAX_DICE_PER_ROLL,
  MAX_THROW_FORCE,
  MIN_THROW_FORCE,
  DicePhysicsWorld,
  RollPlanner,
  RollPlanningError,
  createD6Collider,
  createDiceCollider,
  resolveStabilityConfig,
  type BackgroundRollPlannerOptions,
  type BackgroundRollPlanningTiming,
  type DiceArenaBoundaryPoint,
  type DicePhysicsConfig,
  type DirectRollPlannerOptions,
  type DicePhysicsWorldOptions,
  type PhysicsQuaternion,
  type PhysicsVector3,
  type RollInitialState,
  type RollInitialStateContext,
  type RollInitialStateProvider,
  type RollPlan,
  type RollPlanDie,
  type RollPlannerOptions,
  type RollPlanningOptions,
  type RollPlanningWorkerFactory,
  type RollPlanningWorkerLike,
  type StabilityConfig,
  type StabilityOptions,
  type StabilityResult
} from "./physics/index.js";
export {
  DiceRollPlaybackError,
  DiceRollPlayer,
  type DiceAnimationScheduler,
  type DiceRenderTarget,
  type DiceRollPlaybackDieResult,
  type DiceRollPlaybackOptions,
  type DiceRollPlaybackResult,
  type DiceRollPlayerOptions
} from "./player/index.js";
export {
  DiceMeshFactory,
  DiceRenderer,
  DiceScene,
  type D6MeshOptions,
  type DiceMesh,
  type DiceMeshFactoryOptions,
  type DiceMeshOptions,
  type DiceAmbientLightOptions,
  type DiceCameraOptions,
  type DiceDirectionalLightOptions,
  type DiceLightingOptions,
  type DiceLightPosition,
  type DicePointLightOptions,
  type DiceQuaternion,
  type DiceRendererOptions,
  type DiceSceneLightOptions,
  type DiceSceneOptions,
  type DiceTableBoundaryPoint,
  type DiceTableMaterialOptions,
  type DiceTextureLoader,
  type DiceTransform,
  type DiceVector3,
  type DiceWebGLRendererFactory
} from "./three/index.js";
