export {
  DEFAULT_DICE_APPEARANCE,
  DEFAULT_DICE_FACE_LABEL_MODE,
  DEFAULT_DICE_FONT_APPEARANCE,
  hasDiceTextureSources,
  mergeDiceAppearances,
  resolveDiceAppearance,
  resolveDiceFaceLabelMode,
  resolveDiceFontAppearance,
  type DiceAppearance,
  type DiceFaceLabelMode,
  type DiceFontAppearance,
  type ResolvedDiceAppearance,
  type ResolvedDiceFontAppearance
} from "./appearance/index.js";
export {
  DiceRoller,
  D6_FACE_NORMALS,
  D6_FACE_VALUES,
  D6_OPPOSITE_FACE,
  SUPPORTED_DICE_SIDES,
  SeededRandomProvider,
  createSeededRandomProvider,
  getD6TopValue,
  getDiceFace,
  getDiceTopology,
  getDiceValueFromOrientation,
  type D6FaceNormal,
  type D6FaceValue,
  type DiceDefinition,
  type DiceResultDirection,
  type DiceRollerOptions,
  type DiceRollRequest,
  type DiceRollResult,
  type DiceSides,
  type DiceTopology,
  type DiceTopologyFace,
  type DiceVector3 as DiceTopologyVector3,
  type DieResult,
  type QuaternionLike,
  type RandomProvider,
  type RandomSeed,
  type RollIdProvider
} from "./core/index.js";
export {
  DICE_ROLL_EVENT_TYPE,
  DICE_ROLL_EVENT_VERSION,
  DICE_ROLL_REPLAY_VERSION,
  createDiceRollEvent,
  diceRollResultFromEvent,
  validateDiceRollEvent,
  type CreateDiceRollEventOptions,
  type DiceRollEvent,
  type DiceRollEventDie,
  type DiceRollReplayV1
} from "./events/index.js";
export {
  DiceOverlay,
  DiceOverlayError,
  type DiceOverlayErrorPhase,
  type DiceOverlayOptions,
  type DiceOverlayPlanner,
  type DiceOverlayPlayer,
  type DiceOverlayPlayerFactory,
  type DiceOverlayRenderer,
  type DiceOverlayRendererFactory,
  type DiceOverlayRoller
} from "./overlay/index.js";
export {
  DEFAULT_DICE_PHYSICS_CONFIG,
  DEFAULT_STABILITY_CONFIG,
  DicePhysicsWorld,
  RollPlanner,
  RollPlanningError,
  createD6Collider,
  createDiceCollider,
  resolveStabilityConfig,
  type DicePhysicsConfig,
  type DicePhysicsWorldOptions,
  type PhysicsQuaternion,
  type PhysicsVector3,
  type RollInitialState,
  type RollInitialStateContext,
  type RollInitialStateProvider,
  type RollPlan,
  type RollPlanDie,
  type RollPlannerOptions,
  type StabilityConfig,
  type StabilityOptions,
  type StabilityResult
} from "./physics/index.js";
export {
  DiceRollPlaybackError,
  DiceRollPlayer,
  type DiceAnimationScheduler,
  type DiceRenderTarget,
  type DiceRollPlaybackDieResult,
  type DiceRollPlaybackOptions,
  type DiceRollPlaybackResult,
  type DiceRollPlayerOptions
} from "./player/index.js";
export {
  DiceMeshFactory,
  DiceRenderer,
  DiceScene,
  type D6MeshOptions,
  type DiceMesh,
  type DiceMeshFactoryOptions,
  type DiceMeshOptions,
  type DiceQuaternion,
  type DiceRendererOptions,
  type DiceSceneOptions,
  type DiceTextureLoader,
  type DiceTransform,
  type DiceVector3,
  type DiceWebGLRendererFactory
} from "./three/index.js";
